server:
  port: 9003
spring:
  application:
    name: issue
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.17.131:3306/crown?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.131:2001
  redis:
    host: 192.168.17.131
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  main:
    allow-bean-definition-overriding: true